type TermOfUse = {
    title: string;
    effectiveDate: string;
    introduction: string;
    sections: Array<{
        title: string;
        number: number;
        content: Array<{
            id: string;
            text: string;
            subItems?: string[];
        }>;
    }>;
};

// Example usage:
export const termsOfUse: TermOfUse = {
    title: "Terms of Use",
    effectiveDate: "2022-01-01",
    introduction: "Welcome to Gappii (\"Platform\"). By accessing or using our Platform, you agree to comply with these Terms of Use. Please read them carefully.",
    sections: [
        {
            title: "User Accounts",
            number: 1,
            content: [
                {
                    id: "1.1",
                    text: "To access our Platform, you must create an account using a valid email address or social platform account."
                },
                {
                    id: "1.2",
                    text: "You must be at least 13 years old to use the Platform."
                },
                {
                    id: "1.3",
                    text: "Accounts are personal and non-transferable. You are responsible for maintaining the security of your account."
                }
            ]
        },
        {
            title: "Content Creation and Ownership",
            number: 2,
            content: [
                {
                    id: "2.1",
                    text: "Users can create lessons using the Platform's AI tools or customize/edit them."
                },
                {
                    id: "2.2",
                    text: "Ownership of created lessons is shared between the user and the Platform."
                },
                {
                    id: "2.3",
                    text: "Lessons can be shared via a sharable link generated by the Platform."
                }
            ]
        },
        {
            title: "AI Content Generation",
            number: 3,
            content: [
                {
                    id: "3.1",
                    text: "The Platform uses OpenAI's API to assist in generating lesson content."
                },
                {
                    id: "3.2",
                    text: "Users are responsible for reviewing and ensuring the accuracy of AI-generated content before sharing."
                },
                {
                    id: "3.3",
                    text: "The Platform disclaims liability for any inaccuracies, inappropriate content, or misuse of AI-generated lessons."
                }
            ]
        },
        {
            title: "Prohibited Activities",
            number: 4,
            content: [
                {
                    id: "4.1",
                    text: "Users are prohibited from:",
                    subItems: [
                        "Engaging in illegal activities or promoting content that violates human rights.",
                        "Using the Platform to create or share hateful, defamatory, or inappropriate content."
                    ]
                },
                {
                    id: "4.2",
                    text: "User interactions are limited to copying public lessons, liking, translating and favoriting. Misuse of these features is prohibited."
                }
            ]
        },
        {
            title: "Intellectual Property",
            number: 5,
            content: [
                {
                    id: "5.1",
                    text: "The design, features, and tools of the Platform are the exclusive intellectual property of Gappii."
                },
                {
                    id: "5.2",
                    text: "The Platform's AI capabilities rely on OpenAI's API, and users must comply with their terms of use."
                }
            ]
        },
        {
            title: "Privacy and Data",
            number: 6,
            content: [
                {
                    id: "6.1",
                    text: "The Platform collects the following data: name, email address, lesson activities, and user interactions."
                },
                {
                    id: "6.2",
                    text: "By using the Platform, you consent to the collection and use of this data as outlined in these Terms."
                }
            ]
        },
        {
            title: "Liability",
            number: 7,
            content: [
                {
                    id: "7.1",
                    text: "The Platform is not responsible for any errors, omissions, or inaccuracies in lessons created or shared by users."
                },
                {
                    id: "7.2",
                    text: "The Platform is not liable for service interruptions, data loss, or misuse of lessons."
                }
            ]
        },
        {
            title: "Payment and Subscriptions",
            number: 8,
            content: [
                {
                    id: "8.1",
                    text: "During the beta version, the Platform is free to use."
                },
                {
                    id: "8.2",
                    text: "After the official release, the Platform will operate on a subscription-based model. Details will be provided in future updates."
                }
            ]
        },
        {
            title: "Termination of Service",
            number: 9,
            content: [
                {
                    id: "9.1",
                    text: "The Platform reserves the right to terminate accounts for misuse, illegal activities, or violations of these Terms."
                },
                {
                    id: "9.2",
                    text: "Public lessons will remain accessible even if the user's account is terminated."
                }
            ]
        },
        {
            title: "Governing Law",
            number: 10,
            content: [
                {
                    id: "10.1",
                    text: "These Terms are governed by the laws of France."
                },
                {
                    id: "10.2",
                    text: "Any disputes arising from these Terms will be resolved under the jurisdiction of French courts."
                }
            ]
        }
    ]
};

